n=int(input("enter the total values")) 
t=()
l=list(t)
print("enter the values") 
for i in range(n):
    l.append(int(input())
r=int(input("enter the value to remove")) 
l.remove(r)
t=tuple(l)
print(t) 
